from __future__ import annotations

import os
from pathlib import Path
from dataclasses import dataclass

DESKVANE_ENV_SCRIPT = Path(os.path.expanduser("~/.deskvane_env.sh"))
BASHRC = Path(os.path.expanduser("~/.bashrc"))
ZSHRC = Path(os.path.expanduser("~/.zshrc"))

@dataclass
class TerminalProxyStatus:
    enabled: bool

class TerminalProxyManager:
    """Manages appending DeskVane's shell hook and writing proxy states."""

    @staticmethod
    def setup_hooks() -> None:
        """Ensure bashrc and zshrc source the DeskVane script."""
        hook_cmd = f"\n# DeskVane Terminal Proxy Hook\n[ -f {DESKVANE_ENV_SCRIPT} ] && source {DESKVANE_ENV_SCRIPT}\n"
        
        for rc in (BASHRC, ZSHRC):
            if not rc.exists():
                continue
            try:
                content = rc.read_text("utf-8")
                if "DeskVane Terminal Proxy Hook" not in content:
                    rc.write_text(content + hook_cmd, "utf-8")
            except Exception:
                pass
                
        # Ensure the script at least exists
        if not DESKVANE_ENV_SCRIPT.exists():
            TerminalProxyManager.disable()

    @staticmethod
    def _write_env(address: str, enable_export: bool) -> None:
        lines = [
            "# Auto-generated by DeskVane. Do not edit manually.",
            f'alias proxy="export http_proxy={address} https_proxy={address} all_proxy={address}"',
            'alias unproxy="unset http_proxy https_proxy all_proxy"',
            ""
        ]
        if enable_export:
            lines.extend([
                f"export http_proxy={address}",
                f"export https_proxy={address}",
                f"export all_proxy={address}",
            ])
        DESKVANE_ENV_SCRIPT.write_text("\n".join(lines) + "\n", "utf-8")

    @staticmethod
    def get_status() -> TerminalProxyStatus:
        if not DESKVANE_ENV_SCRIPT.exists():
            return TerminalProxyStatus(enabled=False)
        content = DESKVANE_ENV_SCRIPT.read_text("utf-8")
        is_enabled = "\nexport http_proxy=" in content or content.startswith("export http_proxy=")
        return TerminalProxyStatus(enabled=is_enabled)

    @staticmethod
    def enable(address: str) -> None:
        TerminalProxyManager._write_env(address, enable_export=True)

    @staticmethod
    def disable(address: str | None = None) -> None:
        if address is None:
            # Read the current address from the existing env script
            try:
                content = DESKVANE_ENV_SCRIPT.read_text("utf-8")
                import re
                match = re.search(r'http_proxy=(\S+)', content)
                address = match.group(1).strip('"\'') if match else "http://127.0.0.1:7890"
            except Exception:
                address = "http://127.0.0.1:7890"
        TerminalProxyManager._write_env(address, enable_export=False)
